name: Test Upload Result
description: Test Upload Result

inputs:
  os:
    description: 'The operating system to use'
    required: true
  architecture:
    description: 'The operating system to use'
    required: true
  runtime-type:
    description: 'The operating system to use'
    required: true
  target_framework:
    description: 'The operating system to use'
    required: true
  build_configuration:
    description: 'The build configuration to use'
    required: true
  experimental:
    description: 'The build configuration to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{success() || failure()}}
      with:
        name: ${{(inputs.experimental && 'experimental-') || ''}}test-results-${{inputs.runtime-type}}-${{inputs.os}}-${{inputs.architecture}}-${{inputs.target_framework}}-${{inputs.build_configuration}}
        path: '**/*.trx'
        if-no-files-found: ${{(inputs.experimental && 'ignore') || 'warn'}}
