name: Convert Target Framework to Channel
description: Convert Target Framework to Channel

inputs:
  target_framework_array:
    description: 'The target framework to use'
    required: true

outputs:
  channels_multiline:
    description: 'The converted Channels variable'
    value: ${{steps.set_channels.outputs.channels_multiline}}

runs:
  using: "composite"
  steps:
    - name: Set Channels
      id: set_channels
      run: |
        $EOF = -join (1..15 | ForEach {[char]((48..57)+(65..90)+(97..122) | Get-Random)});
        "channels_multiline<<$EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append;
        foreach ($target_framework in ConvertFrom-Json "${{inputs.target_framework_array}}") {
            $target_framework.Replace('coreapp', '').Replace('net', '') | Out-File -FilePath $env:GITHUB_OUTPUT -Append;
        }
        "$EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append;
      shell: pwsh
