name: Convert Target Framework to Channel
description: Convert Target Framework to Channel

inputs:
  target_framework_array:
    description: 'The target framework to use'
    required: true

outputs:
  channel:
    description: 'The converted Channels variable'
    value: ${{ steps.set_channels.outputs.channels_multiline }}

runs:
  using: "composite"
  steps:
    - name: Set Channels
      id: set_channels
      run: |
        $channels = '';
        $data = ConvertFrom-Json '${{inputs.target_framework_array}}';
        foreach ($target_framework in $data) {
            $channels = $channels + $target_framework.Replace('coreapp', '').Replace('net', '') + '/n';
        }
        "channels_multiline=$channels" | Out-File -FilePath $env:GITHUB_OUTPUT -Append;
      shell: pwsh
