name: Unix .NET

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string

jobs:
  unix-net:
    name: .NET ${{ inputs.image }}-${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: ${{inputs.image}}
    env:
      run_settings_args: 'NUnit.DefaultTestNamePattern="{C}:{m}{a}" RunConfiguration.TargetPlatform=${{inputs.architecture}}'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Sdk
        uses: actions/setup-dotnet@v3

      - run: |
          $channel = '${{inputs.target_framework}}'.Replace('coreapp', '').Replace('net', '');
          "{channel}=$channel" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Setup .NET
        if: startsWith(inputs.image, 'ubuntu') || startsWith(inputs.image, 'macos')
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.channel}}

      - name: Build
        run: |
          dotnet build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} Harmony.sln

      - name: Test .NET
        run: |
          dotnet test Harmony.sln --no-build --configuration ${{inputs.build_configuration}} --framework ${{inputs.target_framework}} --logger "console;verbosity=normal" --blame -- ${{env.run_settings_args}}
