name: Template Testing Windows Mono

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string

jobs:
  windows-mono:
    name: Mono ${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Sdk
        uses: actions/setup-dotnet@v4

      - name: Set ProgramFiles env
        run: |
          if ('${{ inputs.architecture == 'x86'}}' -eq 'true') {
            $programfiles = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::ProgramFilesX86);
            "programfiles=$programfiles" | Out-File -FilePath $env:GITHUB_ENV -Append;
          }
          if ('${{ inputs.architecture == 'x64'}}' -eq 'true') {
            $programfiles = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::ProgramFiles);
            "programfiles=$programfiles" | Out-File -FilePath $env:GITHUB_ENV -Append;
          }
    
      - name: Setup Mono x86
        if: inputs.architecture == 'x86'
        run: |
          curl -L https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0-gtksharp-2.12.45-win32-0.msi -o mono.msi;
          $file = "mono.msi" 
          $log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()

      - name: Setup Mono x64
        if: inputs.architecture == 'x64'
        run: |
          curl -L https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0.199-x64-0.msi -o mono.msi;
          $file = "mono.msi" 
          $log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()

      #- name: Build
      #  run: |
      #    dotnet build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} Harmony.sln

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows-${{inputs.build_configuration}}
          path: ./

      - name: Test Mono
        run: |
          shopt -s failglob globstar
          set -x
          
          # Execute the tests via mono + vstest.console.
          mono="${{env.programfiles}}/Mono/bin/mono.exe"
          vstest="$(vswhere.exe -latest -property installationPath)/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"
          "$mono" "$vstest" "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" --Framework:${{inputs.target_framework}} --logger:trx --blame -- ${{inputs.run_settings_args}}
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-${{inputs.os}}-${{inputs.architecture}}-${{inputs.target_framework}}-${{inputs.build_configuration}}
          path: 'HarmonyTests/TestResults/*.trx'
