name: Template Testing Windows .NET Framework

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string
      upload_tests:
        required: false
        type: boolean
        default: true

jobs:
  windows-net-framework:
    name: .NET FX ${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Sdk
        uses: actions/setup-dotnet@v4
     
      #- name: Build
      #  run: |
      #    dotnet build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} Harmony.sln

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows-${{inputs.build_configuration}}
          path: ./

      - name: Test .NET Framework
        run: |
          vstest="$(vswhere.exe -latest -property installationPath)/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"
          "$vstest" "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" --framework:${{inputs.target_framework}} --logger:trx --logger:"console;verbosity=normal" --results-directory:"./tests" --blame -- ${{inputs.run_settings_args}}
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{inputs.upload_tests && (success() || failure())}}
        with:
          name: test-results-fx-windows-${{inputs.architecture}}-${{inputs.target_framework}}-${{inputs.build_configuration}}
          path: './tests/**/*.trx'
