name: Template Testing Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Build
        run: |
          dotnet build -c ${{inputs.build_configuration}} Harmony.sln

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{inputs.os}}-${{inputs.build_configuration}}
          path: ./*/bin/**/*
