name: Template Testing Windows Mono

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string
      upload_tests:
        required: false
        type: boolean
        default: true
      continue_on_error:
        required: false
        type: boolean
        default: false

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  windows-mono:
    name: Mono ${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-latest
    continue-on-error: ${{inputs.continue_on_error}}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Sdk
        uses: actions/setup-dotnet@v4

      - name: Set ProgramFiles env
        run: |
          if ('${{ inputs.architecture == 'x86'}}' -eq 'true') {
            $programfiles = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::ProgramFilesX86);
            "programfiles=$programfiles" | Out-File -FilePath $env:GITHUB_ENV -Append;
          }
          if ('${{ inputs.architecture == 'x64'}}' -eq 'true') {
            $programfiles = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::ProgramFiles);
            "programfiles=$programfiles" | Out-File -FilePath $env:GITHUB_ENV -Append;
          }

      - name: Setup Mono x86 Manually
        if: inputs.architecture == 'x86'
        run: |
          curl -L https://download.mono-project.com/archive/mono-latest-x86-preview.msi -o mono.msi;
          $file = "mono.msi" 
          $log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()

      - name: Setup Mono x64 Manually
        if: inputs.architecture == 'x64'
        run: |
          curl -L https://download.mono-project.com/archive/mono-latest-x64-preview.msi -o mono.msi;
          $file = "mono.msi" 
          $log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()

      - name: Download Build Cache
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows-${{inputs.build_configuration}}
          path: HarmonyTests/bin/

      - name: Test Mono
        run: |
          shopt -s failglob globstar
          set -x
          
          # Execute the tests via mono + vstest.console.
          mono="${{env.programfiles}}/Mono/bin/mono.exe";
          vstest="$(vswhere.exe -latest -property installationPath)/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe";
          "$mono" "$vstest" "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" --framework:${{inputs.target_framework}} --logger:trx --logger:"console;verbosity=normal" --blame -- ${{inputs.run_settings_args}};
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{inputs.upload_tests && (success() || failure())}}
        with:
          name: test-results-mono-windows-${{inputs.architecture}}-${{inputs.target_framework}}-${{inputs.build_configuration}}
          path: '**/*.trx'
