name: Template Testing Windows .NET

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string
      upload_tests:
        required: false
        type: boolean
        default: true
      experimental:
        required: false
        type: boolean
        default: false

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  unix-net:
    name: .NET ${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-latest
    continue-on-error: ${{inputs.experimental}}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Shared Test Setup
        uses: ./.github/actions/test-setup-shared
        with:
          os: windows
          build_configuration: ${{inputs.build_configuration}}
        
      - uses: ./.github/actions/get-program-files
        id: get-program-files
        with:
          architecture: ${{inputs.architecture}}

      - uses: ./.github/actions/get-dotnet-channel
        id: get_channel
        with:
          target_framework: ${{inputs.target_framework}}

      - name: Setup .NET STS ${{inputs.architecture}}
        uses: ./.github/actions/test-setup-dotnet-windows
        with:
          architecture: ${{inputs.architecture}}
          channel: STS
          program-files: ${{steps.get-program-files.outputs.path}}
          
      - name: Setup .NET LTS ${{inputs.architecture}}
        uses: ./.github/actions/test-setup-dotnet-windows
        with:
          architecture: ${{inputs.architecture}}
          channel: LTS
          program-files: ${{steps.get-program-files.outputs.path}}
         
      - name: Setup .NET ${{steps.get_channel.outputs.channel}} ${{inputs.architecture}}
        uses: ./.github/actions/test-setup-dotnet-windows
        with:
          architecture: ${{inputs.architecture}}
          channel: ${{steps.get_channel.outputs.channel}}
          program-files: ${{steps.get-program-files.outputs.path}}

      - name: Test .NET ${{inputs.architecture}}
        run: |
          dotnet test "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" -f ${{inputs.target_framework}} -l trx -l "console;verbosity=normal" --blame -- ${{inputs.run_settings_args}};

      - name: Upload Test Result
        uses: ./.github/actions/test-upload-result
        if: ${{inputs.upload_tests}}
        with:
          os: windows
          architecture: ${{inputs.architecture}}
          target_framework: ${{inputs.target_framework}}
          build_configuration: ${{inputs.build_configuration}}
          experimental: ${{inputs.experimental}}
