name: Template Testing Windows .NET Framework

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string

jobs:
  windows-net-framework:
    name: .NET FX ${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Sdk
        uses: actions/setup-dotnet@v3
     
      #- name: Build
      #  run: |
      #    dotnet build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} Harmony.sln

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows-${{inputs.build_configuration}}
          path: ./

      - name: Test .NET Framework
        run: |
          vstest="$(vswhere.exe -latest -property installationPath)/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"
          "$vstest" "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" --Framework:${{inputs.target_framework}} --logger:trx --ResultsDirectory:"${{ github.workspace }}/TestResults" --blame -- ${{inputs.run_settings_args}}
        shell: bash

      #- name: Parse Trx files
      #  uses: NasAmin/trx-parser@v0.5.0
      #  with:
      #    TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
      #    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
