name: Template Testing Result Upload

on:
  workflow_call:

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: ./test-results

      - name: Test Report Upload
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Tests
          path: 'test-results/**/*.trx'
          reporter: dotnet-trx
