name: Template Testing Result Upload

on:
  workflow_call:
    inputs:
      experimental:
        required: false
        type: boolean
        default: false

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results ${{inputs.experimental && '(Experimental)'}}
          files: ${{inputs.experimental && 'experimental-'}}test-results/**/*.trx
