name: Template Testing Result Upload

on:
  workflow_call:
    inputs:
      experimental:
        required: false
        type: boolean
        default: false
        description: 'Whether the tests are mandatory for the build to pass'

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: ${{(inputs.experimental && 'experimental-') || ''}}test-results-*
          path: test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results ${{(inputs.experimental && '(Experimental)') || ''}}
          files: test-results/**/*.trx
          fail_on: ${{(inputs.experimental && 'nothing') || 'test failures'}}
          #ignore_runs: ${{inputs.experimental}}
          check_run: ${{!inputs.experimental}}
          comment_mode: ${{(inputs.experimental && 'off') || 'always'}}
          #check_run_annotations: ${{(inputs.experimental && 'none') || 'all tests, skipped tests'}}
