name: Template Testing Unix .NET

on:
  workflow_call:
    inputs:
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string
      upload_tests:
        required: false
        type: boolean
        default: true
      continue_on_error:
        required: false
        type: boolean
        default: false

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  unix-net:
    name: .NET ubuntu-arm64 ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs.continue_on_error}}
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4

      - name: Set Channel env
        run: |
          $channel = '${{inputs.target_framework}}'.Replace('coreapp', '').Replace('net', '');
          "channel=$channel" | Out-File -FilePath $env:GITHUB_ENV -Append;
        shell: pwsh

      - name: Download Build Cache
        uses: actions/download-artifact@v4
        with:
          name: build-output-ubuntu-${{inputs.build_configuration}}
          path: HarmonyTests/bin/

      - uses: uraimo/run-on-arch-action@v2.7.1
        name: Run commands
        id: build
        with:
          arch: aarch64
          distro: ubuntu22.04
          shell: /bin/bash
          env: |
            DOTNET_NOLOGO: ${{env.DOTNET_NOLOGO}}
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: ${{env.DOTNET_SKIP_FIRST_TIME_EXPERIENCE}}
            DOTNET_CLI_TELEMETRY_OPTOUT: ${{env.DOTNET_CLI_TELEMETRY_OPTOUT}}
          dockerRunArgs: |
            --volume "${PWD}/src:/src"
          install: |
            apt-get update
            apt-get install -y wget libc6 libgcc-s1 libgssapi-krb5-2 libicu70 liblttng-ust1 libssl3 libstdc++6 libunwind8 zlib1g
       
            wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh;
            chmod +x dotnet-install.sh;
            ./dotnet-install.sh --channel STS --no-path > /dev/null;
            ./dotnet-install.sh --channel LTS --no-path > /dev/null;
            ./dotnet-install.sh --channel ${{env.channel}} --no-path > /dev/null;
          run: |
            LD_LIBRARY_PATH="/usr/local/lib"  /root/.dotnet/dotnet test "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" -f ${{inputs.target_framework}} -l trx -l "console;verbosity=normal" --blame -- ${{inputs.run_settings_args}};

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        #if: ${{inputs.upload_tests && (success() || failure())}}
        if: ${{inputs.upload_tests && success()}}
        with:
          name: test-results-net-ubuntu-arm64-${{inputs.target_framework}}-${{inputs.build_configuration}}
          path: '**/*.trx'
