name: Template Testing Unix .NET

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      image:
        required: true
        type: string
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      run_settings_args:
        required: true
        type: string

jobs:
  unix-net:
    name: .NET ${{ inputs.os }}-${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: ${{inputs.image}}
    steps:
      - uses: actions/checkout@v4

      - name: Set Channel env
        run: |
          $channel = '${{inputs.target_framework}}'.Replace('coreapp', '').Replace('net', '');
          "channel=$channel" | Out-File -FilePath $env:GITHUB_ENV -Append;
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.channel}}

      #- name: Build
      #  run: |
      #    dotnet build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} Harmony.sln

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output-${{inputs.os}}-${{inputs.build_configuration}}
          path: ./

      - name: Test .NET
        run: |
          dotnet test Harmony.sln --no-build -c ${{inputs.build_configuration}} -f ${{inputs.target_framework}} --logger trx --blame -- ${{inputs.run_settings_args}}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-net-${{inputs.os}}-${{inputs.architecture}}-${{inputs.target_framework}}-${{inputs.build_configuration}}
          path: '**/*.trx'
