name: Windows .NET Framework

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      build_configuration:
        required: true
        type: string

jobs:
  windows-net-framework:
    name: .NET FX Windows-${{ inputs.architecture }} ${{ inputs.target_framework }} ${{ inputs.build_configuration }}
    runs-on: windows-2019
    continue-on-error: true
    env:
      run_settings_args: 'NUnit.DefaultTestNamePattern="{C}:{m}{a}" RunConfiguration.TargetPlatform=${{inputs.architecture}}'
    steps:
      - uses: actions/checkout@v2
     
      - name: Build
        run: |
          dotnet build -c ${{inputs.build_configuration}} --framework ${{inputs.target_framework}} Harmony.sln

      - name: Test .NET Framework
        run: |
          vstest="$(vswhere.exe -latest -property installationPath)/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"
          "$vstest" "HarmonyTests/bin/Release/${{inputs.target_framework}}/HarmonyTests.dll" --Framework:${{inputs.target_framework}} --logger:trx --ResultsDirectory:"$RUNNER_TEMP" --blame -- ${{inputs.run_settings_args}}
        shell: bash
